server:
  port: 9091
spring:
    application:
       name: cn-keygenerator
    redis:
      host: 127.0.0.1
      port: 6379
      jedis:
        pool:
          max-active: 20
          max-idle: 8
          min-idle: 1
